spring.application.name=sistema_venta

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/sistema_ventas?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/Lima&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=ZmFrZS1zZWNyZXQta2V5LXBhcmEtc2lzdGVtYS12ZW50YXMtMjAyNi1od3MyNTYtY2xhdmU
jwt.expiration=86400000
jwt.header=Authorization
jwt.prefix=Bearer

# Server
server.port=8080

# Consulta DNI/RUC-10 en línea
consulta.dni.url=https://eldni.com/pe/buscar-datos-por-dni
consulta.ruc10.url=https://eldni.com/pe/buscar-nombres-por-ruc-10
consulta.intervalo-ms=1500
