spring.application.name=sistema_venta

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/sistema_ventas?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/Lima&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=ZmFrZS1zZWNyZXQta2V5LXBhcmEtc2lzdGVtYS12ZW50YXMtMjAyNi1od3MyNTYtY2xhdmU
jwt.expiration=86400000
jwt.header=Authorization
jwt.prefix=Bearer

# Server
server.port=8080

# ApisPeru (consulta DNI/RUC)
apisperu.url=https://dniruc.apisperu.com/api/v1
apisperu.token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InlveGFuMTQzM0BnbWFpbC5jb20ifQ.fO3B0UqNRg83DkdVDn_HQj5sjcwI7GsQ1R0Tq4HGriM
